/**
 * Offline city data: bundled coordinates for geocoding without a network, and
 * monthly climate normals as a fallback for the weather lookup when Open-Meteo is
 * unreachable (offline, or the `file://` single-file copy whose null origin the
 * archive API rejects). Data is generated by `scripts/gen-city-data.mjs`.
 *
 * This is a coarse fallback: highs/lows come from monthly normals (so daily
 * extremes are smoothed) and there is no wind data, so the "windy" tag never
 * fires offline. Online lookups are unaffected.
 */
import type { DailyWeather, GeoResult } from './weather';
import geoRaw from '../data/geo-cities.json';
import climateRaw from '../data/climate-cities.json';

export interface MonthNormal {
  hi: number;
  lo: number;
  rain: number;
  dry: number;
}

export interface ClimateCity {
  name: string;
  cc: string;
  lat: number;
  lon: number;
  months: MonthNormal[];
}

// Beyond this, a destination is treated as having no nearby normals (the 104
// climate cities are sparse, so a far match would be a different climate).
const DEFAULT_MAX_KM = 750;

type GeoTuple = [name: string, cc: string, lat: number, lon: number];
type ClimateTuple = [...GeoTuple, months: [number, number, number, number][]];

const country = (cc: string): string | undefined => {
  try {
    return new Intl.DisplayNames(['en'], { type: 'region' }).of(cc) ?? undefined;
  } catch {
    return undefined;
  }
};

/** Bundled major cities (name → coords) for offline geocoding. */
export const GEO_CITIES: GeoResult[] = (geoRaw as GeoTuple[]).map(([name, cc, lat, lon]) => ({
  name,
  lat,
  lon,
  countryCode: cc,
  country: country(cc),
}));

/** Bundled monthly climate normals for the offline weather fallback. */
export const CLIMATE_CITIES: ClimateCity[] = (climateRaw as ClimateTuple[]).map(
  ([name, cc, lat, lon, months]) => ({
    name,
    cc,
    lat,
    lon,
    months: months.map(([hi, lo, rain, dry]) => ({ hi, lo, rain, dry })),
  }),
);

const toRad = (deg: number): number => (deg * Math.PI) / 180;

/** Great-circle distance between two lat/lon points, in kilometres. */
export function haversineKm(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const R = 6371;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const lat1 = toRad(aLat);
  const lat2 = toRad(bLat);
  const h =
    Math.sin(dLat / 2) ** 2 + Math.sin(dLon / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** The climate city closest to a point, or null if none is within `maxKm`. */
export function nearestClimateCity(
  lat: number,
  lon: number,
  cities: ClimateCity[] = CLIMATE_CITIES,
  maxKm: number = DEFAULT_MAX_KM,
): ClimateCity | null {
  let best: ClimateCity | null = null;
  let bestKm = Infinity;
  for (const c of cities) {
    const km = haversineKm(lat, lon, c.lat, c.lon);
    if (km < bestKm) {
      bestKm = km;
      best = c;
    }
  }
  return best && bestKm <= maxKm ? best : null;
}

/**
 * An evenly-spaced boolean pattern marking `wetDays` of `daysInMonth` as wet, so
 * rainfall lands on a representative fraction of any sub-window of the month.
 */
export function monthWetPattern(daysInMonth: number, wetDays: number): boolean[] {
  const out = new Array<boolean>(daysInMonth).fill(false);
  if (wetDays <= 0) return out;
  if (wetDays >= daysInMonth) return out.fill(true);
  let acc = 0;
  for (let i = 0; i < daysInMonth; i++) {
    acc += wetDays;
    if (acc >= daysInMonth) {
      acc -= daysInMonth;
      out[i] = true;
    }
  }
  return out;
}

const daysInMonth = (year: number, monthIdx: number): number =>
  new Date(year, monthIdx + 1, 0).getDate();

/**
 * Synthesize a daily series for a date range from a city's monthly normals:
 * each day takes its month's average high/low, monthly rainfall is spread over an
 * even pattern of wet days, and wind is always 0 (no offline wind data).
 */
export function climateDailyForRange(
  city: ClimateCity,
  range: { startDate: string; endDate: string },
): DailyWeather {
  const out: DailyWeather = { tMax: [], tMin: [], precip: [], wind: [] };
  const end = new Date(range.endDate + 'T00:00:00');
  for (let d = new Date(range.startDate + 'T00:00:00'); d <= end; d.setDate(d.getDate() + 1)) {
    const m = d.getMonth();
    const mn = city.months[m];
    if (!mn) continue;
    const dim = daysInMonth(d.getFullYear(), m);
    const wetDays = Math.min(Math.max(dim - mn.dry, 0), dim);
    const wet = monthWetPattern(dim, wetDays)[d.getDate() - 1];
    out.tMax.push(mn.hi);
    out.tMin.push(mn.lo);
    out.precip.push(wet && wetDays > 0 ? mn.rain / wetDays : 0);
    out.wind.push(0);
  }
  return out;
}

/** Offline geocoding: match the bundled city list by name (prefix first). */
export function localSearchCities(
  query: string,
  count = 8,
  cities: GeoResult[] = GEO_CITIES,
): GeoResult[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const prefix: GeoResult[] = [];
  const substr: GeoResult[] = [];
  for (const c of cities) {
    const name = c.name.toLowerCase();
    if (name.startsWith(q)) prefix.push(c);
    else if (name.includes(q)) substr.push(c);
  }
  return [...prefix, ...substr].slice(0, count);
}
